# WF for deploying to production

name: Deploy to production

on:
  pull_request:
    types:
      - closed

jobs:
  call-reusable:
    uses: deckhouse/hugo-web-product-module/.github/workflows/deploy-prod.yaml@main
