# WF for deploying to test/stage envs on PR label 'deploy/test' or 'deploy/stage'

name: Deploy to dev environments

on:
  pull_request_target:
    types:
      - labeled

jobs:
  call-reusable:
    uses: deckhouse/hugo-web-product-module/.github/workflows/deploy-dev.yaml@main